// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihpexsvmwllavtnjtvqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlocGV4c3Ztd2xsYXZ0bmp0dnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTc0NzQsImV4cCI6MjA2NTAzMzQ3NH0.NIOsQnNTD1rROlLI3KXXvzck8cF2qoJoa3NF5l1V5r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);